"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
import sys
from django.contrib.messages import constants as messages
from google.oauth2 import service_account

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#This loads environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

# CORRECTED settings.py line
ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,peachesncream-782513543316.europe-southwest1.run.app'
).split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django.contrib.staticfiles',
    # Other
    'materializecssform',
    'crispy_forms',
    'crispy_forms_materialize',
    'djrichtextfield',
    # Apps
    'home',
    'grocery_list',
    'contact',
]

SITE_ID = 1

# Account Setup

ACCOUNT_EMAIL_VERIFICATION = 'none'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'

DJRICHTEXTFIELD_CONFIG = {
    'js': ['//cdn.ckeditor.com/4.14.0/standard/ckeditor.js'],
    'init_template': 'djrichtextfield/init/ckeditor.js',
    'settings': {
        'toolbar': [
            ['NumberedList', 'BulletedList'], ['Undo', 'Redo'],
            ['Maximize']
        ],
    }
}

CRISPY_TEMPLATE_PACK = 'materialize_css_forms'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates', 'allauth')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'crispy_forms.templatetags.crispy_forms_tags',
                'crispy_forms.templatetags.crispy_forms_field'
            ]
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# Google Cloud Storage Settings
# Retrieve GS_BUCKET_NAME from environment variables loaded by python-dotenv
GS_BUCKET_NAME = os.environ.get('GS_BUCKET_NAME')
# Retrieve GS_PROJECT_ID if needed (optional)
GS_PROJECT_ID = os.environ.get('GS_PROJECT_ID', 'applications-461317') # Use the project ID from your key file for clarity

# --- BEGIN GCS CONFIG BLOCK ---
if GS_BUCKET_NAME:
    print("DEBUG: GS_BUCKET_NAME is set. Starting GCS configuration.", file=sys.stderr)

    # 1. Define the path where the secret (keyfile) is mounted in Cloud Run.
    # NOTE: Your key file name in the secret JSON you provided was 'DJANGO_GCS_KEY1.json', 
    # but the path should be the full mount path (e.g., /etc/secrets/DJANGO_GCS_KEY1.json)
    # The default value here should match the full path set in Cloud Run Volume Mounts
    GCS_KEYFILE_PATH = os.environ.get('GCS_KEYFILE_PATH', '/etc/secrets/DJANGO_GCS_KEY1') 

    # 2. Explicitly load credentials from the mounted JSON key file.
    GCS_CREDENTIALS = None 
    
    # Perform the check using the configured path
    if os.path.exists(GCS_KEYFILE_PATH):
        print(f"DEBUG: Key file found at {GCS_KEYFILE_PATH}. Attempting to load credentials...", file=sys.stderr)
        try:
            # Load the credentials from the mounted file
            GCS_CREDENTIALS = service_account.Credentials.from_service_account_file(GCS_KEYFILE_PATH)
            print("DEBUG: GS_CREDENTIALS successfully created from file.", file=sys.stderr)

        except Exception as e:
            # CRITICAL: This will expose if the JSON is malformed or the library fails
            print(f"FATAL ERROR: Failed to load service account file: {e}", file=sys.stderr) 

    else:
        # Fallback for local testing or if the file isn't found (THIS IS YOUR SUSPECTED FAILURE POINT)
        print(f"WARNING: GCS key file NOT found at {GCS_KEYFILE_PATH}. Falling back to default credentials.", file=sys.stderr)

    # 3. Configure storages and pass the credentials
    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    
    # PASS THE EXPLICIT CREDENTIALS OBJECT
    if GCS_CREDENTIALS:
        GS_CREDENTIALS = GCS_CREDENTIALS
    
    # NEW: Add the service account email (required for signing even with explicit credentials)
    # Use the email from the JSON file you provided:
    GS_SA_EMAIL = 'peachesncream-srv-gcs@applications-461317.iam.gserviceaccount.com' 
    
    # Your other settings
    GS_PROJECT_ID = GS_PROJECT_ID
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/media/'
    STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/static/'

else:
    print("DEBUG: GS_BUCKET_NAME not set. Skipping GCS configuration.", file=sys.stderr)
# --- END GCS CONFIG BLOCK ---

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
