# Generated by Django 3.2.20 on 2023-08-07 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My grocery list', max_length=500)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('school', 'School'), ('hardware', 'Hardware'), ('travel', 'Travel'), ('gifts', 'Gifts'), ('decoration', 'Decoration'), ('lifestyle', 'Lifestyle'), ('wishlist', 'Wishlist')], default='groceries', max_length=20)),
                ('shop', models.CharField(blank=True, max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', djrichtextfield.models.RichTextField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
