# Generated by Django 3.2.18 on 2023-04-27 16:13

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='item',
            field=djrichtextfield.models.RichTextField(max_length=5000),
        ),
    ]
