# Generated by Django 3.2.20 on 2023-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_auto_20230427_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='grocery',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
