# Generated by Django 3.2.20 on 2023-08-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0009_grocery_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='lists',
        ),
    ]
